# -*- coding: utf-8 -*-
"""Github用教育サイトjson実装版.ipynb  のコピー

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsmeK250EtCrQBjIEpeh0IqB8EAIgzuh

ブロック１
**【必要ライブラリのインポート】**
"""

!pip install streamlit
import random
import json
import streamlit as st # 💡 ipywidgetsの代わりにStreamlitをインポート
# import pandas as pd # データがシンプルなら不要ですが、大規模なら残してもOK

# --- 状態管理の初期化 ---
# ページ遷移や現在のクイズの状態を管理するために Streamlitのセッションステートを初期化
if 'page' not in st.session_state:
    st.session_state.page = 'selection' # selection / quiz / result
    st.session_state.current_q = 0
    st.session_state.score = 0
    st.session_state.quiz_data = [] # 実行中のクイズデータ
    st.session_state.feedback = None # 回答後のフィードバック情報

"""ブロック２
**【クイズ内容の定義】**
"""

# 💡 修正: クイズデータの外部JSONファイル名を設定
QUIZ_FILE = 'jsonファイル.json'

# コースの選択肢
COURSE_OPTIONS = [5, 10, 20]

# Streamlitがデータをキャッシュし、高速化するデコレーター
@st.cache_data
def load_quiz_data(file_path):
    """JSONファイルからクイズデータを読み込み、リスト形式で返す関数"""
    try:
        # Colabではなく、デプロイ先（GitHub）のファイルを開く
        with open(file_path, 'r', encoding='utf-8') as file:
            quiz_list = json.load(file)
            print(f"✅ クイズデータ {len(quiz_list)} 件を外部ファイルから正常に読み込みました。")
            return quiz_list
    except FileNotFoundError:
        st.error(f"❌ エラー: クイズファイル '{file_path}' が見つかりません。GitHubにアップロードされているか確認してください。")
        return []
    except json.JSONDecodeError:
        st.error(f"❌ エラー: クイズファイル '{file_path}' の形式が不正です。")
        return []

# 外部ファイルからデータを読み込み、既存の変数に格納
quiz_data_all = load_quiz_data(QUIZ_FILE)

if not quiz_data_all:
     st.warning("⚠️ 警告: クイズデータが読み込めませんでした。プログラムは動作しますがクイズは実行できません。")

"""ブロック３
**【変数とロジックを制御する関数】**
"""

# --- クイズの起動とコース選択画面 ---

def start_quiz(num_questions):
    """選択されたコースに基づいてクイズを開始する関数"""

    # データをシャッフルし、選択された数だけ問題を取得
    if num_questions > len(quiz_data_all):
        selected_questions = quiz_data_all[:]
    else:
        selected_questions = random.sample(quiz_data_all, num_questions)

    # 状態を初期化してクイズ画面へ遷移
    st.session_state.quiz_data = selected_questions
    st.session_state.total_questions = len(selected_questions)
    st.session_state.current_q = 0
    st.session_state.score = 0
    st.session_state.feedback = None
    st.session_state.page = 'quiz'


# --- 回答のチェックと状態更新 ---

def check_answer(selected_index):
    """回答をチェックし、フィードバックを設定する関数"""
    q_data = st.session_state.quiz_data[st.session_state.current_q]
    is_correct = (selected_index == q_data['answer_index'])

    if is_correct:
        st.session_state.score += 1
        feedback_status = '✅ 正解です！'
    else:
        feedback_status = '❌ 不正解です。'

    # フィードバックを状態に保存
    st.session_state.feedback = {
        'status': feedback_status,
        'rationale': q_data['rationale']
    }
    # 次の質問へ進む準備
    st.session_state.current_q += 1


# --- 画面描画関数 ---

def display_selection_page():
    """コース選択画面の描画（Streamlitコンポーネントで構築）"""
    st.title('💡 コース選択')
    st.write("何問で情報リテラシー・クイズに挑戦しますか？")

    # URLを表示 (Colabでの表示は不要だが、Streamlitで情報として表示する)
    st.info(f'このアプリは Streamlit Cloud で公開されています。') # 💡 修正: 公開サービスのURLを推奨

    # コースボタンを横並びで配置
    cols = st.columns(len(COURSE_OPTIONS))
    for col, num in zip(cols, COURSE_OPTIONS):
        if num > len(quiz_data_all):
             description = f'全{len(quiz_data_all)}問コース'
        else:
             description = f'{num}問コース'

        # Streamlitのボタン。クリックされたら start_quiz を呼び出し、画面を再実行
        if col.button(description, key=f"course_{num}"):
            start_quiz(num)
            st.rerun() # 画面全体を再実行してクイズ画面へ遷移

def display_quiz_page():
    """クイズ画面の描画（Streamlitコンポーネントで構築）"""

    # ページが切り替わった直後、または全問終了の場合の処理
    if st.session_state.current_q >= st.session_state.total_questions:
        st.session_state.page = 'result'
        st.rerun() # 結果画面へ強制遷移
        return

    q_index = st.session_state.current_q # 現在表示すべき質問のインデックス
    q_data = st.session_state.quiz_data[q_index]

    st.subheader(f"Q{q_index + 1} / {st.session_state.total_questions}: {q_data['question']}")

    # --- 選択肢ボタンの表示と回答処理 ---
    # フィードバックが表示されている場合はボタンを押せないようにする
    disable_buttons = st.session_state.feedback is not None

    for i, option_text in enumerate(q_data['options']):
        # Streamlitのボタン: クリックされたらチェック関数を呼び出し、再描画
        if st.button(f"[{i + 1}] {option_text}", key=f"q_{q_index}_opt_{i}", disabled=disable_buttons):
            check_answer(i)
            st.rerun() # 画面全体を再実行してフィードバックを表示

    # --- フィードバックの表示エリア ---
    if st.session_state.feedback:
        fb = st.session_state.feedback

        # 正誤に応じた表示
        if fb['status'].startswith('✅'):
             st.success(fb['status'])
        else:
             st.error(fb['status'])

        # 解説の表示
        st.info(f"【解説】 {fb['rationale']}")

        # 次の質問へ進むボタン
        if st.button("次の質問へ", key="next_q_button"):
            # feedbackをクリアして、画面全体を再実行 (次の質問が表示される)
            st.session_state.feedback = None
            st.rerun()

def display_result_page():
    """最終結果を表示する関数"""
    st.balloons()
    st.title('✅ 全問終了！お疲れ様でした！')
    st.markdown(
        f'<p style="font-size: 24px; color: darkorange;">あなたのスコア: **{st.session_state.score} / {st.session_state.total_questions}** 点</p>',
        unsafe_allow_html=True
    )
    st.write('AI時代の情報リテラシー向上に向けて、一緒に学んでいきましょう！')

    # コース選択画面に戻るボタン
    if st.button("コース選択に戻る"):
        st.session_state.page = 'selection'
        st.rerun() # 画面全体を再実行してコース選択画面へ

"""ブロック４**【クイズ実行】**"""

# --- メイン処理：現在のページに応じて描画 ---
# Streamlitはファイル全体を上から順に実行するため、このブロックがページの切り替えを制御します。

if st.session_state.page == 'selection':
    display_selection_page()
elif st.session_state.page == 'quiz':
    display_quiz_page() # クイズとフィードバックの表示ロジックを実行
elif st.session_state.page == 'result':
    display_result_page()