# -*- coding: utf-8 -*-
"""教育サイトjson実装版.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEJyG8eQ5cEfEv9G6_4Uuwf3zug2hgHP

ブロック１
**【必要ライブラリのインポート】**
"""

import random
import ipywidgets as widgets
from IPython.display import display, clear_output
import json # 💡 追加: JSONファイルを扱うために必要

"""ブロック２
**【クイズ内容の定義】**
"""

"""ブロック２
**【クイズ内容の定義】**
"""

import json # 💡 JSONファイルを扱うために必要 (ブロック1に移動しても可)

# 💡 修正: クイズデータの外部JSONファイル名を 'quiz_800.json' に変更
QUIZ_FILE = 'jsonファイル.json'

def load_quiz_data(file_path):
    """JSONファイルからクイズデータを読み込み、リスト形式で返す関数"""
    try:
        # Colabにアップロードされたファイルを開き、JSONとして読み込む
        with open(file_path, 'r', encoding='utf-8') as file:
            quiz_list = json.load(file)
            print(f"✅ クイズデータ {len(quiz_list)} 件を外部ファイルから正常に読み込みました。")
            return quiz_list
    except FileNotFoundError:
        # ファイルが見つからない場合のエラー処理
        print(f"❌ エラー: クイズファイル '{file_path}' が見つかりません。")
        print("    Google Colabの左側のファイルパネルにアップロードされているか確認してください。")
        return []
    except json.JSONDecodeError:
        # JSON形式が不正な場合のエラー処理
        print(f"❌ エラー: クイズファイル '{file_path}' の形式が不正です。JSONの内容を確認してください。")
        return []

# 外部ファイルからデータを読み込み、既存の変数に格納
# 元々あった巨大な quiz_data_all リストの定義がこの一行に置き換わります
quiz_data_all = load_quiz_data(QUIZ_FILE)

if not quiz_data_all:
     print("⚠️ 警告: クイズデータが読み込めませんでした。プログラムは動作しますがクイズは実行できません。")

"""ブロック３
**【変数とロジックを制御する関数】**
"""

"""ブロック３
**【変数とロジックを制御する関数】**
"""

# --- グローバル変数と初期設定 ---
# 実行するクイズデータ (選択されたコースによって内容が変わる)
quiz_data = []
current_question_index = 0
score = 0
total_questions = 0

# 【変更】このColabノートブックのURLを一般的なサイトURLに修正
COLAB_URL = "https://example.com/your-quiz-site" # 💡 修正: ここを実際のサイトURLに置き換えてください

# 結果を表示するためのOutputウィジェット
output = widgets.Output()
course_options = [5, 10, 20]


# --- クイズの起動とコース選択画面 ---

def start_quiz(num_questions):
    """選択されたコースに基づいてクイズを開始する関数"""
    global quiz_data, total_questions, current_question_index, score

    # データをシャッフルし、選択された数だけ問題を取得
    if num_questions > len(quiz_data_all):
        selected_questions = quiz_data_all[:]
    else:
        selected_questions = random.sample(quiz_data_all, num_questions)

    quiz_data = selected_questions
    total_questions = len(quiz_data)
    current_question_index = 0
    score = 0

    display_question()


def display_course_selection():
    """コース選択画面を表示する関数"""
    title_html = widgets.HTML("<h1>コース選択</h1>")
    subtitle_html = widgets.HTML("<p>何問で情報リテラシー・クイズに挑戦しますか？</p>")

    # URLを表示 (変数は変更されているが、表示ロジックは変わらない)
    url_html = widgets.HTML(f'<p>👉 このクイズサイトのURL: <a href="{COLAB_URL}" target="_blank">{COLAB_URL}</a></p>')

    buttons = []
    for num in course_options:
        if num > len(quiz_data_all):
             description = f'全{len(quiz_data_all)}問コース'
        else:
             description = f'🧠 {num}問コース'

        button = widgets.Button(description=description, button_style='primary')
        # ボタンがクリックされたら start_quiz を呼び出す
        button.on_click(lambda b, n=num: start_quiz(n))
        button.style.button_color = '#00796B'
        buttons.append(button)

    course_box = widgets.VBox(buttons) # 縦に並べるVBoxを使用

    with output:
        clear_output(wait=True)
        # URLウィジェットを追加
        display(title_html, subtitle_html, url_html, course_box)


# --- クイズの表示とロジックを制御する関数 ---

def display_question():
    """現在の質問を表示する関数"""
    global current_question_index

    if current_question_index >= total_questions:
        display_results()
        return

    q_data = quiz_data[current_question_index]

    question_html = widgets.HTML(f"<h2>Q{current_question_index + 1} / {total_questions}: {q_data['question']}</h2>")

    # --- 選択肢のシャッフルロジック ---
    options_with_index = []
    original_answer_index = q_data['answer_index']

    # (選択肢テキスト, 元のインデックス) のタプルを作成
    for i, option_text in enumerate(q_data['options']):
        options_with_index.append((option_text, i))

    # 💡 選択肢のリストをランダムにシャッフル
    random.shuffle(options_with_index)

    # シャッフル後のリストから新しい正解インデックスを探す
    shuffled_options = [item[0] for item in options_with_index]
    shuffled_answer_index = -1 # 初期化

    for i, (_, original_index) in enumerate(options_with_index):
        if original_index == original_answer_index:
            shuffled_answer_index = i
            break

    # --- 選択肢の表示とクリックイベントの作成 ---
    option_widgets = []
    # 💡 シャッフルされた選択肢のリストを使用
    for i, option_text in enumerate(shuffled_options):

        # 1. 選択肢テキスト（HTMLを使用し、確実に折り返す）
        option_label_html = widgets.HTML(
            # white-space: normal; で折り返しを強制
            value=f'<div style="font-size: 16px; font-weight: bold; padding: 10px; white-space: normal;">'
                  f'[{i + 1}] {option_text}'
                  f'</div>',
            layout=widgets.Layout(width='100%')
        )

        # 2. クリックイベントを担うボタン
        click_button = widgets.Button(
            description="選択する",
            button_style='info',
            layout=widgets.Layout(width='100%', height='auto', min_height='35px'),
            style=widgets.ButtonStyle(button_color='#00796B', text_color='white')
        )

        # クリックイベント設定: 選択したインデックス (i) とシャッフル後の正解インデックスを渡す
        click_button.on_click(lambda b, index=i, answer=shuffled_answer_index, data=q_data: check_answer(index, answer, data))

        # 3. テキストとボタンをセットにしたVBoxを一つの選択肢とする
        option_container = widgets.VBox([
            option_label_html,
            click_button
        ], layout=widgets.Layout(border='2px solid #00796B', margin='10px 0', padding='0'))

        option_widgets.append(option_container)

    # 💡 質問画面からコース選択に戻るボタンを、選択肢と同じ形状で追加
    back_to_course_label = widgets.HTML(
        value=f'<div style="font-size: 16px; font-weight: bold; padding: 10px; white-space: normal; color: #B71C1C;">'
              f'↩ コース選択に戻る'
              f'</div>',
        layout=widgets.Layout(width='100%')
    )
    back_to_course_button = widgets.Button(
        description="このクイズを中断する",
        button_style='danger',
        layout=widgets.Layout(width='100%', height='auto', min_height='35px'),
        style=widgets.ButtonStyle(button_color='#B71C1C', text_color='white')
    )
    back_to_course_button.on_click(lambda b: display_course_selection())
    back_to_course_container = widgets.VBox([
        back_to_course_label,
        back_to_course_button
    ], layout=widgets.Layout(border='2px solid #B71C1C', margin='10px 0', padding='0'))
    option_widgets.append(back_to_course_container)

    options_vbox = widgets.VBox(option_widgets)

    # 質問の全要素をVBoxコンテナで包んで表示
    quiz_elements = widgets.VBox([question_html, options_vbox])

    with output:
        clear_output(wait=True)
        display(quiz_elements)


def check_answer(selected_index, shuffled_answer_index, q_data):
    """回答をチェックし、結果と解説を表示する関数"""
    global current_question_index, score

    # 💡 修正: シャッフル後の正解インデックスと比較
    is_correct = (selected_index == shuffled_answer_index)

    feedback_html = widgets.HTML()
    next_button = widgets.Button(description="▶ 次の質問へ", button_style='success')

    # 💡 追加: 解説画面からコース選択に戻るボタン
    back_to_course_button_feedback = widgets.Button(
        description="🏠 コース選択画面に戻る (中断)",
        button_style='danger',
        layout=widgets.Layout(width='auto', min_height='35px')
    )
    back_to_course_button_feedback.on_click(lambda b: display_course_selection())

    if is_correct:
        feedback_html.value = '<h3 style="color: green;">✅ 正解です！</h3>'
        score += 1
    else:
        # 💡 修正: 不正解の場合、正解の選択肢を表示するロジック
        original_answer_text = q_data['options'][q_data['answer_index']]
        feedback_html.value = (
            '<h3 style="color: red;">❌ 不正解です。</h3>'
            f'<p style="font-size: 18px; color: green; font-weight: bold;">'
            f'正解: {original_answer_text}'
            f'</p>'
        )

    rationale_html = widgets.HTML(
        f'<p style="border: 2px solid #4CAF50; padding: 15px; background-color: #E8F5E9; border-radius: 5px; color: #006400;">'
        f'<strong>【解説】</strong> {q_data["rationale"]}'
        f'</p>'
    )

    next_button.on_click(lambda b: next_question())

    # ボタンを横に並べるHBox
    action_buttons = widgets.HBox([next_button, back_to_course_button_feedback])

    # フィードバックの全要素をVBoxコンテナでまとめて描画安定性を高める
    feedback_elements = widgets.VBox([feedback_html, rationale_html, action_buttons])

    with output:
        clear_output(wait=True)
        display(feedback_elements)


def next_question():
    """質問番号を増やして次の質問を表示する関数"""
    global current_question_index
    current_question_index += 1
    display_question()


def display_results():
    """最終結果を表示する関数"""
    result_html = widgets.HTML(
        f'<h1 style="color: navy;">全問終了！お疲れ様でした！</h1>'
        f'<p style="font-size: 20px;">あなたのスコア: <strong style="color: darkorange;">{score} / {total_questions}</strong> 点</p>'
    )

    # コース選択画面に戻るボタン
    restart_button = widgets.Button(description="🏠 コース選択画面に戻る", button_style='primary')
    restart_button.on_click(lambda b: display_course_selection())

    with output:
        clear_output(wait=True)
        display(result_html, restart_button)

"""ブロック４**【クイズ実行】**"""

# Colabのセルに出力ウィジェットを表示し、初期画面を呼び出す
display(output)
display_course_selection()
